// <auto-generated />
using System;
using CheckAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckAPI.Infrastructure.Migrations
{
    [DbContext(typeof(CheckAPIContext))]
    [Migration("20240229012317_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Entities.RelatorioDeInspecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ultima_modificacao");

                    b.Property<Guid>("InspecaoId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id_inspecao");

                    b.HasKey("Id");

                    b.HasIndex("InspecaoId");

                    b.ToTable("relatorio_inspecao", (string)null);
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ultima_modificacao");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("funcionarios", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Inspecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<byte?>("Conclusao")
                        .HasColumnType("tinyint")
                        .HasColumnName("conclusao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ultima_modificacao");

                    b.Property<Guid>("IdExecutor")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id_executor");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdExecutor");

                    b.ToTable("inspecoes", (string)null);
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Executor", b =>
                {
                    b.HasBaseType("CheckAPI.Domain.Inspecoes.Funcionario");

                    b.HasDiscriminator().HasValue("Executor");
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Entities.RelatorioDeInspecao", b =>
                {
                    b.HasOne("CheckAPI.Domain.Inspecoes.Inspecao", "Inspecao")
                        .WithMany("Relatorios")
                        .HasForeignKey("InspecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspecao");
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Inspecao", b =>
                {
                    b.HasOne("CheckAPI.Domain.Inspecoes.Executor", "Executor")
                        .WithMany("Inspecoes")
                        .HasForeignKey("IdExecutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Inspecao", b =>
                {
                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("CheckAPI.Domain.Inspecoes.Executor", b =>
                {
                    b.Navigation("Inspecoes");
                });
#pragma warning restore 612, 618
        }
    }
}
